### 1 TYPE GET TODOS
GET http://localhost:3004/todos

### 2 TYPE GET TODO
GET http://localhost:3004/todos/e5331d6e-e8a1-4935-98f8-091dc0b8e6b5

### 1 TYPE POST TODOS (Create a new todo)
POST http://localhost:3004/todos
Content-Type: application/json

{
  "content": "mi nuevo todo",
  "done": false
}

###METHOD DELETE REMOVE A TODO

DELETE http://localhost:3004/todos
Content-Type: application/json

{
  "id": "18f09ae3-55fc-4474-9322-fc29872ea20b"
}

###METHOD PATCH CHANGE DONE PROPERTY VAL !CONTRARY

PATCH http://localhost:3004/todos
Content-Type: application/json

{
  "id": "84475a99-edc9-4f3c-b1de-6e1d4e0df15a"
}